name: auto_fit_data_table
description: DataTable which automatically resizes based on the window size.
version: 0.0.2
homepage: https://github.com/AdamVe/auto_fit_data_table

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

